name: payment-service-frontend

services:
  payment-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:8081/api}
    container_name: payment-service-frontend
    ports:
      - "${FRONTEND_PORT:-5173}:80"
    restart: unless-stopped
